services:
  db:
    image: mysql:8.0
    container_name: cine_share_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cine_share
      MYSQL_USER: cineuser
      MYSQL_PASSWORD: cinepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cine_share_network

volumes:
  mysql_data:

networks:
  cine_share_network:
